<?php

namespace Database\Seeders;

use App\Models\Context;
use App\Models\Role;
use Illuminate\Database\Seeder;

class AdminSubRolesSeeder extends Seeder
{
    /**
     * Crea (o actualiza) los roles administrativos especializados del club
     * (subconjuntos de admin_club) y sincroniza sus permisos. Seguro de correr
     * múltiples veces.
     */
    public function run(): void
    {
        $webContextId = Context::firstOrCreate([
            'value' => 'web',
        ], [
            'name' => 'Web',
            'value' => 'web',
        ])->id;

        $roles = [
            'Gerente Cobranza Parque I' => [
                'description' => 'Rol para persona encargada de la cobranza a nivel administrativo',
                'permissions' => [
                    "profile.show",
                    "fee-schedules.index",
                    "fee-schedules.store",
                    "fee-schedules.annual-discount-rules",
                    "accounts.view",
                    "members.view",
                    "documents.view",
                    "absences.view",
                    "clinical-history.view",
                    "history.view",
                    "lockers-history.view",
                    "members.cancel",
                    "members.reactivate",
                    "members.cancellations.index",
                    "members.age-transitions.index",
                    "members.documents.store",
                    "members.age-transitions.promote",
                    "members.age-transitions.dismiss",
                    "members.lockers.create",
                    "members.lockers.store",
                    "members.lockers.change",
                    "members.lockers.reserve",
                    "lockers.available",
                    "lockers.assigned.by.account",
                    "lockers.available.for.change",
                    "members.index",
                    "members.create",
                    "members.store",
                    "members.edit",
                    "members.update",
                    "members.destroy",
                    "members.lockers.history",
                    "acts.index",
                    "acts.store",
                    "acts.update",
                    "memberships.view-inscription-fee",
                    "collections.index",
                    "collections.store",
                    "billing.payments.non-cash-cut",
                    "reports.index",
                    "billing-concepts.index",
                    "billing-concepts.store",
                    "billing-concepts.update",
                    "payment-methods.index",
                    "payment-methods.store",
                    "payment-methods.update",
                    "tickets.index",
                    "payments.cancel",
                    "cash-cuts.index",
                    "cash-cuts.store",
                    "cash-cuts.show",
                    "cash-cuts.close",
                    "cash-cuts.view-all",
                    "global-cash-cuts.index",
                    "global-cash-cuts.store",
                    "global-cash-cuts.show",
                    "global-cash-cuts.close",
                    "members.cancel.create",
                    "members.additional-membership.create",
                    "day-passes.incidents.index",
                    "day-passes.incidents.store",
                    "members.lockers.remove",
                ],
            ],
            'Gerente Cobranza Parque II' => [
                'description' => 'Rol para persona encargada de la cobranza a nivel administrativo',
                'permissions' => [
                    "profile.show",
                    "fee-schedules.index",
                    "fee-schedules.store",
                    "fee-schedules.annual-discount-rules",
                    "document-types.index",
                    "document-types.store",
                    "document-types.update",
                    "membership-types.index",
                    "membership-types.update",
                    "accounts.view",
                    "members.view",
                    "documents.view",
                    "absences.view",
                    "clinical-history.view",
                    "history.view",
                    "lockers-history.view",
                    "members.cancel",
                    "members.reactivate",
                    "members.cancellations.index",
                    "members.age-transitions.index",
                    "members.documents.store",
                    "members.age-transitions.promote",
                    "members.age-transitions.dismiss",
                    "members.lockers.create",
                    "members.lockers.store",
                    "members.lockers.change",
                    "members.lockers.reserve",
                    "lockers.available",
                    "lockers.assigned.by.account",
                    "lockers.available.for.change",
                    "members.index",
                    "members.create",
                    "members.store",
                    "members.edit",
                    "members.update",
                    "members.destroy",
                    "members.lockers.history",
                    "acts.index",
                    "acts.store",
                    "acts.update",
                    "collections.index",
                    "collections.store",
                    "billing.payments.non-cash-cut",
                    "reports.index",
                    "billing-concepts.index",
                    "billing-concepts.store",
                    "billing-concepts.update",
                    "payment-methods.index",
                    "payment-methods.store",
                    "payment-methods.update",
                    "tickets.index",
                    "payments.cancel",
                    "cash-cuts.index",
                    "cash-cuts.store",
                    "cash-cuts.show",
                    "cash-cuts.close",
                    "cash-cuts.view-all",
                    "global-cash-cuts.index",
                    "global-cash-cuts.store",
                    "global-cash-cuts.show",
                    "global-cash-cuts.close",
                    "members.cancel.create",
                    "members.additional-membership.create",
                    "day-passes.incidents.index",
                    "day-passes.incidents.store",
                    "members.lockers.remove",
                ]
            ],

            'Amenidades, publicidad, reservaciones Parque I' => [
                'description' => 'Rol para amenidades, publicidad, reservaciones, encuestas, del Parque I',
                'permissions' => [
                    "profile.show",
                    "club-settings.edit",
                    "club-settings.update",
                    "amenities.index",
                    "amenities.store",
                    "amenities.update",
                    "amenities.destroy",
                    "amenityResource.index",
                    "amenityResource.store",
                    "amenityResource.update",
                    "amenityResource.destroy",
                    "amenityResource.calendar",
                    "blockedPeriods.index",
                    "blockedPeriods.store",
                    "blockedPeriods.update",
                    "blockedPeriods.destroy",
                    "amenitySchedule.store",
                    "amenityResource.generateQr",
                    "amenityResource.downloadQrPdf",
                    "amenityResource.downloadQr",
                    "coaches.index",
                    "coaches.store",
                    "coaches.update",
                    "coaches.destroy",
                    "reservations.index",
                    "reservations.store",
                    "reservations.update",
                    "reservations.cancel",
                    "reservations.calendar",
                    "announcements.index",
                    "announcements.store",
                    "announcements.update",
                    "announcements.destroy",
                    "announcements.storeGallery",
                    "announcements.getGallery",
                    "announcements.destroyGalleryImage",
                    "app-variables.index",
                    "app-variables.update",
                    "system-variables.index",
                    "system-variables.update",
                    "member-access.index",
                    "member-access.store",
                    "member-access.reset-password",
                    "member-access.destroy",
                    "surveys.index",
                    "surveys.create",
                    "surveys.store",
                    "surveys.edit",
                    "surveys.update",
                    "surveys.destroy",
                    "surveys.results",
                    "surveys.questions.store",
                    "surveys.questions.update",
                    "surveys.questions.destroy",
                    "surveys.questions.reorder",
                    "business-ads.index",
                    "business-ads.approve",
                    "business-ads.reject",
                    "business-categories.index",
                    "business-categories.store",
                    "business-categories.update",
                    "business-categories.destroy",
                    "feedback-categories.index",
                    "feedback-categories.store",
                    "feedback-categories.update",
                    "feedback-categories.destroy",
                    "feedback-ticket-types.index",
                    "feedback-ticket-types.store",
                    "feedback-ticket-types.update",
                    "feedback-ticket-types.destroy",
                    "feedback-statuses.index",
                    "feedback-statuses.store",
                    "feedback-statuses.update",
                    "feedback-statuses.destroy",
                    "feedback-priorities.index",
                    "feedback-priorities.store",
                    "feedback-priorities.update",
                    "feedback-priorities.destroy",
                    "feedback.index",
                    "feedback.store",
                    "feedback.update",
                    "feedback.destroy",
                    "feedback-management.index",
                    "feedback-management.update",
                    "website-content.index",
                    "website-content.store",
                    "website-content.destroy",
                    "website-contacts.index"
                ]
            ],
            'Amenidades, publicidad, reservaciones Parque II' => [
                'description' => 'Rol para amenidades, publicidad, reservaciones, encuestas, del Parque II',
                'permissions' => [
                    "profile.show",
                    "club-settings.edit",
                    "club-settings.update",
                    "amenities.index",
                    "amenities.store",
                    "amenities.update",
                    "amenities.destroy",
                    "amenityResource.index",
                    "amenityResource.store",
                    "amenityResource.update",
                    "amenityResource.destroy",
                    "amenityResource.calendar",
                    "blockedPeriods.index",
                    "blockedPeriods.store",
                    "blockedPeriods.update",
                    "blockedPeriods.destroy",
                    "amenitySchedule.store",
                    "amenityResource.generateQr",
                    "amenityResource.downloadQrPdf",
                    "amenityResource.downloadQr",
                    "coaches.index",
                    "coaches.store",
                    "coaches.update",
                    "coaches.destroy",
                    "reservations.index",
                    "reservations.store",
                    "reservations.update",
                    "reservations.cancel",
                    "reservations.calendar",
                    "announcements.index",
                    "announcements.store",
                    "announcements.update",
                    "announcements.destroy",
                    "announcements.storeGallery",
                    "announcements.getGallery",
                    "announcements.destroyGalleryImage",
                    "app-variables.index",
                    "app-variables.update",
                    "system-variables.index",
                    "system-variables.update",
                    "member-access.index",
                    "member-access.store",
                    "member-access.reset-password",
                    "member-access.destroy",
                    "surveys.index",
                    "surveys.create",
                    "surveys.store",
                    "surveys.edit",
                    "surveys.update",
                    "surveys.destroy",
                    "surveys.results",
                    "surveys.questions.store",
                    "surveys.questions.update",
                    "surveys.questions.destroy",
                    "surveys.questions.reorder",
                    "feedback-categories.index",
                    "feedback-categories.store",
                    "feedback-categories.update",
                    "feedback-categories.destroy",
                    "feedback-ticket-types.index",
                    "feedback-ticket-types.store",
                    "feedback-ticket-types.update",
                    "feedback-ticket-types.destroy",
                    "feedback-statuses.index",
                    "feedback-statuses.store",
                    "feedback-statuses.update",
                    "feedback-statuses.destroy",
                    "feedback-priorities.index",
                    "feedback-priorities.store",
                    "feedback-priorities.update",
                    "feedback-priorities.destroy",
                    "feedback.index",
                    "feedback.store",
                    "feedback.update",
                    "feedback.destroy",
                    "feedback-management.index",
                    "feedback-management.update",
                    "website-content.index",
                    "website-content.store",
                    "website-content.destroy",
                    "website-contacts.index",
                ]
            ],

            'Cobranza' => [
                'description' => 'Rol para persona encargada de la cobranza',
                'permissions' => [
                    "profile.show",
                    "accounts.view",
                    "members.view",
                    "documents.view",
                    "absences.view",
                    "clinical-history.view",
                    "history.view",
                    "lockers-history.view",
                    "members.documents.store",
                    "members.index",
                    "collections.index",
                    "collections.store",
                    "reports.index",
                    "billing-concepts.index",
                    "payment-methods.index",
                    "tickets.index",
                    "cash-cuts.index",
                    "cash-cuts.store",
                    "cash-cuts.show",
                    "cash-cuts.close",
                ]
            ]

        ];

        foreach ($roles as $name => $data) {
            $role = Role::updateOrCreate(
                ['name' => $name],
                [
                    'description' => $data['description'],
                    'context_id' => $webContextId,
                ]
            );
            $role->syncPermissions($data['permissions']);
        }
    }
}
