<?php

namespace Database\Seeders;

use App\Models\Billing\ChargeConcept;
use Illuminate\Database\Seeder;

class BillingConceptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $concepts = [
            [
                'code' => 'MONTHLY_FEE',
                'name' => 'CUOTA MENSUALIDAD',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '01',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'MONTHLY_FEE_INTERMEDIATE',
                'name' => 'CUOTA MENSUALIDAD INTERMEDIO',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '01I',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'MONTHLY_FEE_PASS',
                'name' => 'CUOTA MENS. PASE',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '08',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'MONTHLY_FEE_PASS_INTERMEDIATE',
                'name' => 'CUOTA MENS. PASE  INTERMEDIO',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '08I',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'MONTHLY_FEE_PARKS',
                'name' => ' Cuota Mens Parques',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '80',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'MONTHLY_FEE_PARKS_INTERMEDIATE',
                'name' => '  Cuota Mens Parques Intermedio',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '80I',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'MONTHLY_FEE_PARKS_FI',
                'name' => 'Cuota Mens Parqes F/I',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '81',
                'splits_between_parks' => true,
            ],
            [
                'code' => 'INSCRIPTION',
                'name' => 'Inscripción',
                'description' => 'Cargo de inscripción o alta de membresía.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => true,
                'is_active' => true,
                'internal_key' => '04',
            ],
            [
                'code' => 'BUSINESS_AD',
                'name' => 'Negocio/Publicidad',
                'description' => 'Cargo por promoción de negocio o publicidad.',
                'default_amount' => 200,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'business_ad',
            ],
            [
                'code' => 'LOCKERS',
                'name' => 'CUOTA CASILLERO',
                'description' => 'Cargo anual por renta de un casillero.',
                'default_amount' => 1100,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '02',
            ],
            [
                'code' => 'GUEST_LIST',
                'name' => 'Lista de invitados',
                'description' => 'Cargo por lista de invitados.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'guess_list',
            ],
            [
                'code' => 'CAFETERIA_PASS',
                'name' => 'Cafetería',
                'description' => 'Cargo por acceso a la cafetería.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'cafeteria_pass',
            ],
            [
                'code' => 'OTHER',
                'name' => 'Otros',
                'description' => 'Cargo por concepto no definido.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'other',
            ],
            // event
            [
                'code' => 'EVENT',
                'name' => 'Evento',
                'description' => 'Cargo por evento.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'event',
            ],

            [
                'code' => '01A',
                'name' => 'Cuota anual 2018 pago anticipado',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '01A',
            ],
            // [
            //     'code' => '01B',
            //     'name' => 'Cuota mensualidad',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => false,
            // ],
            // [
            //     'code' => '01I',
            //     'name' => 'Cuota mensualidad intermedio',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '03',
                'name' => 'Cuota credencial',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '03',
            ],
            [
                'code' => '031',
                'name' => 'Cuota repo. credencia',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '031',
            ],
            // [
            //     'code' => '041',
            //     'name' => 'Cuota insc. españoles',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '042',
            //     'name' => 'Cuota insc. beneficen',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '043',
            //     'name' => 'Cuota ins parq. i',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => 'CUOTA_REINSCRIPCION',
                'name' => 'Cuota reinscripción',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '05',
            ],
            [
                'code' => '06',
                'name' => 'Cuota adeudo anterior',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '06',
            ],
            [
                'code' => '061',
                'name' => 'Cuota adeudo ambos pa',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '061',
            ],
            // [
            //     'code' => '063',
            //     'name' => 'Cuota mens parcial',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '07',
                'name' => 'Mov. canc.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '07',
            ],
            // [
            //     'code' => '08',
            //     'name' => 'Cuota mens. pase',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '08I',
            //     'name' => 'Cuota mens. pase intermedio',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '09',
                'name' => 'Cuota permiso',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '09',
            ],
            [
                'code' => '091',
                'name' => 'Cuota 75%permiso',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '091',
            ],
            [
                'code' => '092',
                'name' => 'Cuota permiso ambos parques',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '092',
            ],
            [
                'code' => '093',
                'name' => 'Cuota 75% permiso ambos parques',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '093',
            ],
            [
                'code' => '09I',
                'name' => 'Cuota permiso intermedio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '09I',
            ],
            [
                'code' => '10',
                'name' => 'Cuota cred. gimnasio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '10',
            ],
            [
                'code' => '11',
                'name' => 'Cuota insc.traspaso',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '11',
            ],
            [
                'code' => '12',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12',
            ],
            [
                'code' => '120',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '120',
            ],
            [
                'code' => '121',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '121',
            ],
            [
                'code' => '122',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '122',
            ],
            [
                'code' => '12A',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12A',
            ],
            [
                'code' => '12B',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12B',
            ],
            [
                'code' => '12C',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12C',
            ],
            [
                'code' => '12D',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12D',
            ],
            [
                'code' => '12E',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12E',
            ],
            [
                'code' => '12F',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12F',
            ],
            [
                'code' => '12G',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12G',
            ],
            [
                'code' => '12H',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12H',
            ],
            [
                'code' => '12I',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12I',
            ],
            [
                'code' => '12J',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12J',
            ],
            [
                'code' => '12K',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12K',
            ],
            [
                'code' => '12L',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12L',
            ],
            [
                'code' => '12M',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12M',
            ],
            [
                'code' => '12N',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12N',
            ],
            [
                'code' => '12O',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12O',
            ],
            [
                'code' => '12P',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12P',
            ],
            [
                'code' => '12Q',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12Q',
            ],
            [
                'code' => '12R',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12R',
            ],
            [
                'code' => '12S',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12S',
            ],
            [
                'code' => '12T',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12T',
            ],
            [
                'code' => '12U',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12U',
            ],
            [
                'code' => '12V',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12V',
            ],
            [
                'code' => '12W',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12W',
            ],
            [
                'code' => '12X',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12X',
            ],
            [
                'code' => '12Y',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12Y',
            ],
            [
                'code' => '12Z',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '12Z',
            ],
            [
                'code' => '13',
                'name' => 'Cuota calcomania',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '13',
            ],
            // [
            //     'code' => '14',
            //     'name' => 'Cuota insc. est. inf.',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '15',
                'name' => 'Cuota % est. infantil',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '15',
            ],
            [
                'code' => 'COMISION_CHEQUE_REBOTADO',
                'name' => 'Comision ch. rebot',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '16',
            ],
            [
                'code' => '17',
                'name' => 'Cuota varios - pub.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '17',
            ],
            [
                'code' => '18',
                'name' => 'Comision rechazo tc',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '18',
            ],
            [
                'code' => '20',
                'name' => 'Cuota pase diario',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '20',
            ],
            [
                'code' => '22',
                'name' => 'Cuota pase infantil',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '22',
            ],
            [
                'code' => '23',
                'name' => 'Cuota pase comida',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '23',
            ],
            [
                'code' => '30',
                'name' => 'Cuota renta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '30',
            ],
            [
                'code' => '31',
                'name' => 'Cancela renta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '31',
            ],
            [
                'code' => '32',
                'name' => 'Iva renta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '32',
            ],
            [
                'code' => '33',
                'name' => 'Cuota anuncio ofici',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '33',
            ],
            [
                'code' => '332',
                'name' => 'Cuota 2 anuncio ofici',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '332',
            ],
            [
                'code' => '333',
                'name' => 'Cuota 4 anuncio oficio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '333',
            ],
            [
                'code' => '34',
                'name' => 'Cuota anuncio c carta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '34',
            ],
            [
                'code' => '342',
                'name' => 'Cuota 2 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '342',
            ],
            [
                'code' => '343',
                'name' => 'Cuota 3 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '343',
            ],
            [
                'code' => '344',
                'name' => 'Cuota 4 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '344',
            ],
            [
                'code' => '345',
                'name' => 'Cuota 5 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '345',
            ],
            [
                'code' => '346',
                'name' => 'Cuota 6 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '346',
            ],
            [
                'code' => '34D',
                'name' => 'Cuota anuncio c dcart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '34D',
            ],
            [
                'code' => '34T',
                'name' => 'Cuota 4 anuncio doble carta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '34T',
            ],
            [
                'code' => '35',
                'name' => 'Cuota anuncio c 1/2c',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '35',
            ],
            [
                'code' => '36',
                'name' => 'Cuota renta sombrilla',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '36',
            ],
            [
                'code' => '37',
                'name' => 'Cuota anuncio revista',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '37',
            ],
            [
                'code' => '40',
                'name' => 'Cuota act. dep.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '40',
            ],
            [
                'code' => '50',
                'name' => 'Cuota renta raquetas',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '50',
            ],
            [
                'code' => '500',
                'name' => 'Cuota c.v. color',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '500',
            ],
            // [
            //     'code' => '501',
            //     'name' => 'Cuota insc.c.v.colori',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '502',
                'name' => 'Cuota gtos c.v.colori',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '502',
            ],
            [
                'code' => '51',
                'name' => 'Cuota billar',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '51',
            ],
            // [
            //     'code' => '510',
            //     'name' => 'Cuota insc. futbol dp',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => false,
            // ],
            // [
            //     'code' => '511',
            //     'name' => 'Cuota insc. futbol p1',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => false,
            // ],
            [
                'code' => '541',
                'name' => 'Cuota tenis',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '541',
            ],
            [
                'code' => '542',
                'name' => 'Cuota natacion',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '542',
            ],
            [
                'code' => '543',
                'name' => 'Cuota curso de verano',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '543',
            ],
            [
                'code' => '544',
                'name' => 'Cuota flamenco',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '544',
            ],
            [
                'code' => '545',
                'name' => 'Cuota tae kwon do',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '545',
            ],
            [
                'code' => '546',
                'name' => 'Cuota futbol dp',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '546',
            ],
            [
                'code' => '548',
                'name' => 'Cuota futbol p1',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '548',
            ],
            [
                'code' => '549',
                'name' => 'Cuota jazz',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '549',
            ],
            [
                'code' => '550',
                'name' => 'Cuota inv. cur.verano',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '550',
            ],
            [
                'code' => '551',
                'name' => 'Cuota p1 curs.verano',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '551',
            ],
            [
                'code' => '553',
                'name' => 'Cuota spininng',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '553',
            ],
            [
                'code' => '554',
                'name' => 'Cuota yoga',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '554',
            ],
            [
                'code' => '555',
                'name' => 'Cuota clase spining',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '555',
            ],
            [
                'code' => '556',
                'name' => 'Cuota nat. est. inf.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '556',
            ],
            [
                'code' => '557',
                'name' => 'Cuota visita spa',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '557',
            ],
            [
                'code' => '558',
                'name' => 'Cuota sem c ver',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '558',
            ],
            [
                'code' => '559',
                'name' => 'Cuota sem c ver p1',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '559',
            ],
            [
                'code' => '560',
                'name' => 'Cuota sem c ver invit',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '560',
            ],
            [
                'code' => '561',
                'name' => 'Cuota voleibol',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '561',
            ],
            [
                'code' => '562',
                'name' => 'Cuota zumba',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => '562',
            ],
            [
                'code' => '60',
                'name' => 'Cuota intercambio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '60',
            ],
            [
                'code' => '70',
                'name' => 'Cuota mantto. local',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '70',
            ],
            [
                'code' => '703',
                'name' => 'Cuota mantto. local 3',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '703',
            ],
            [
                'code' => '707',
                'name' => 'Cuota mantto. local 7',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '707',
            ],
            [
                'code' => '708',
                'name' => 'Cuota mantto. local 8',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '708',
            ],
            [
                'code' => '709',
                'name' => 'Cuota mantto. local 9',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '709',
            ],
            [
                'code' => '710',
                'name' => 'Cuota mantto. local 10',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '710',
            ],
            [
                'code' => '711',
                'name' => 'Cuota mantto. local 11',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => '711',
            ],
            [
                'code' => '712',
                'name' => 'Cuota mantto. local 12',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '712',
            ],
            [
                'code' => '713',
                'name' => 'Cuota mantto. local 13',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '713',
            ],
            [
                'code' => '714',
                'name' => 'Cuota mantto. local 14',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '714',
            ],
            [
                'code' => '715',
                'name' => 'Cuota mantto. local 15',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '715',
            ],
            [
                'code' => '716',
                'name' => 'Cuota mantto. local 16',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '716',
            ],
            [
                'code' => '717',
                'name' => 'Cuota mantto. local 17',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '717',
            ],
            [
                'code' => '718',
                'name' => 'Cuota mantto. local 18',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'internal_key' => '718',
            ],
            [
                'code' => '799',
                'name' => 'Uso de espacio de instalaciones',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'internal_key' => '799',
            ],
            // [
            //     'code' => '80',
            //     'name' => 'Cuota mens parques',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '80I',
            //     'name' => 'Cuota mens parques intermedio',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '81',
            //     'name' => 'Cuota mens parqes f/i',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => 'B01',
                'name' => 'Servicio de med. de rehabilitación',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B01',
            ],
            [
                'code' => 'B02',
                'name' => 'Servivio de med. de rehabilitación revaloración',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B02',
            ],
            [
                'code' => 'B03',
                'name' => 'Electromiografía 2 extremidades',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B03',
            ],
            [
                'code' => 'B04',
                'name' => 'Electromiografía 4 extremidades',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B04',
            ],
            [
                'code' => 'B05',
                'name' => 'Aplicación toxina botulínica',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B05',
            ],
            [
                'code' => 'B06',
                'name' => 'Infiltración',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B06',
            ],
            [
                'code' => 'B07',
                'name' => 'Sesión de fisioterapia',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B07',
            ],
            [
                'code' => 'B08',
                'name' => 'Aplicación de tape',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'B08',
            ],
            [
                'code' => 'B09',
                'name' => 'Paq. 10 sesiones de fisioterapia',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'B09',
            ],
            [
                'code' => 'CE',
                'name' => 'Cuota %cons emp h ext',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'CE',
            ],
            [
                'code' => 'CM',
                'name' => 'Cargo por mora',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'CM',
            ],
            [
                'code' => 'CP',
                'name' => 'Cuota % consumo parqu',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'CP',
            ],
            [
                'code' => 'CHEQUE_REBOTADO_PARQUE2',
                'name' => 'Cheque rebotado',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'CR',
            ],
            [
                'code' => 'CHEQUE_REBOTADO_PARQUE1',
                'name' => 'Cheque rebotado parque 1',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'CR1',
            ],
            [
                'code' => 'CTC',
                'name' => 'Comis. t. de c.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'CTC',
            ],
            // [
            //     'code' => 'D01',
            //     'name' => 'Devolucion inscripcion',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => 'DE',
                'name' => 'Descuento',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'DE',
            ],
            [
                'code' => 'IF',
                'name' => 'Cuota indiv. a fam.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'IF',
            ],
            [
                'code' => 'PE',
                'name' => 'Pago por usuarios del parque i',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'PE',
            ],
            [
                'code' => 'PS',
                'name' => 'Cuota % sky',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'PS',
            ],
            [
                'code' => 'VA',
                'name' => 'Venta de activo',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'VA',
            ],
            [
                'code' => 'VR',
                'name' => 'Cuota desperfectos',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'VR', 
            ],
            [
                'code' => 'X02',
                'name' => 'Cuota prom. pub.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'X02',
            ],
            [
                'code' => 'X03',
                'name' => 'Cuota anuncio revista',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'X03',

            ],
            [
                'code' => 'X07',
                'name' => 'Patrocinio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
                'internal_key' => 'X07',
            ],
            // 
            [
                'code' => 'PHYSICAL_AD',
                'name' => 'Anuncio Físico',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
                'internal_key' => 'PHYSICAL_AD',
            ]
        ];

        foreach ($concepts as $concept) {
            // $concept['internal_key'] = $concept['code'];

            // Varios conceptos legados del catálogo importado (import
            // histórico) no traen 'is_active' explícito arriba — se
            // mantiene el mismo default que la columna (true) para no
            // cambiar su comportamiento.
            $concept['is_active'] = $concept['is_active'] ?? true;
            $concept['splits_between_parks'] = $concept['splits_between_parks'] ?? false;
            // is mobile payable just a MONTHLY_FEE
            $concept['is_mobile_payable'] = false;
            if($concept['code'] === 'MONTHLY_FEE') {
                $concept['is_mobile_payable'] = true;
            }
            

            // withTrashed(): si este código ya se había archivado en una
            // corrida anterior de este mismo seeder, hay que encontrarlo
            // para actualizarlo/reactivarlo en vez de intentar crear uno
            // nuevo con el mismo 'code' (violaría el unique).
            $chargeConcept = ChargeConcept::withTrashed()->updateOrCreate(
                ['internal_key' => $concept['internal_key']],
                $concept
            );

            // Los conceptos marcados is_active=false en este catálogo son
            // legados que ya no se deben poder seleccionar ni ver en el
            // listado — se archivan (soft delete) en vez de solo quedar
            // "Inactivo", sin perder el historial de cargos que ya los
            // usaron (ver Charge::concept()/ChargeConceptClubAmount::concept(),
            // que los siguen resolviendo con withTrashed()).
            if (!$concept['is_active']) {
                if (!$chargeConcept->trashed()) {
                    $chargeConcept->delete();
                }
            } elseif ($chargeConcept->trashed()) {
                $chargeConcept->restore();
            }
        }
    }
}
