<?php

namespace Database\Seeders;

use App\Models\Billing\ChargeConcept;
use Illuminate\Database\Seeder;

class BillingConceptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $concepts = [
            [
                'code' => 'MONTHLY_FEE',
                'name' => 'Mensualidad',
                'description' => 'Cargo mensual recurrente de la membresia.',
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'INSCRIPTION',
                'name' => 'Inscripción',
                'description' => 'Cargo de inscripción o alta de membresía.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => true,
                'is_active' => true,
            ],
            [
                'code' => 'BUSINESS_AD',
                'name' => 'Negocio/Publicidad',
                'description' => 'Cargo por promoción de negocio o publicidad.',
                'default_amount' => 200,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'LOCKERS',
                'name' => 'Renta de casilleros',
                'description' => 'Cargo anual por renta de un casillero.',
                'default_amount' => 1100,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'GUEST_LIST',
                'name' => 'Lista de invitados',
                'description' => 'Cargo por lista de invitados.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'CAFETERIA_PASS',
                'name' => 'Cafetería',
                'description' => 'Cargo por acceso a la cafetería.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'OTHER',
                'name' => 'Otros',
                'description' => 'Cargo por concepto no definido.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            // event
            [
                'code' => 'EVENT',
                'name' => 'Evento',
                'description' => 'Cargo por evento.',
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],

            [
                'code' => '01A',
                'name' => 'Cuota anual 2018 pago anticipado',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            // [
            //     'code' => '01B',
            //     'name' => 'Cuota mensualidad',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => false,
            // ],
            // [
            //     'code' => '01I',
            //     'name' => 'Cuota mensualidad intermedio',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '03',
                'name' => 'Cuota credencial',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '031',
                'name' => 'Cuota repo. credencia',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            // [
            //     'code' => '041',
            //     'name' => 'Cuota insc. españoles',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '042',
            //     'name' => 'Cuota insc. beneficen',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '043',
            //     'name' => 'Cuota ins parq. i',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '05',
                'name' => 'Cuota reinscripcion',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '06',
                'name' => 'Cuota adeudo anterior',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '061',
                'name' => 'Cuota adeudo ambos pa',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            // [
            //     'code' => '063',
            //     'name' => 'Cuota mens parcial',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '07',
                'name' => 'Mov. canc.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            // [
            //     'code' => '08',
            //     'name' => 'Cuota mens. pase',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '08I',
            //     'name' => 'Cuota mens. pase intermedio',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '09',
                'name' => 'Cuota permiso',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '091',
                'name' => 'Cuota 75%permiso',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '092',
                'name' => 'Cuota permiso ambos parques',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '093',
                'name' => 'Cuota 75% permiso ambos parques',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '09I',
                'name' => 'Cuota permiso intermedio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '10',
                'name' => 'Cuota cred. gimnasio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '11',
                'name' => 'Cuota insc.traspaso',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '120',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '121',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '122',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12A',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12B',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12C',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12D',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12E',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12F',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12G',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12H',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12I',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12J',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12K',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12L',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12M',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12N',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12O',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12P',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12Q',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12R',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12S',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12T',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12U',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12V',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12W',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12X',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12Y',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '12Z',
                'name' => 'Cuota mantto.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '13',
                'name' => 'Cuota calcomania',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            // [
            //     'code' => '14',
            //     'name' => 'Cuota insc. est. inf.',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '15',
                'name' => 'Cuota % est. infantil',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '16',
                'name' => 'Comision ch. rebot',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '17',
                'name' => 'Cuota varios - pub.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '18',
                'name' => 'Comision rechazo tc',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '20',
                'name' => 'Cuota pase diario',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '22',
                'name' => 'Cuota pase infantil',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '23',
                'name' => 'Cuota pase comida',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '30',
                'name' => 'Cuota renta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '31',
                'name' => 'Cancela renta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '32',
                'name' => 'Iva renta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '33',
                'name' => 'Cuota anuncio ofici',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '332',
                'name' => 'Cuota 2 anuncio ofici',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '333',
                'name' => 'Cuota 4 anuncio oficio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '34',
                'name' => 'Cuota anuncio c carta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '342',
                'name' => 'Cuota 2 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '343',
                'name' => 'Cuota 3 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '344',
                'name' => 'Cuota 4 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '345',
                'name' => 'Cuota 5 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '346',
                'name' => 'Cuota 6 anuncio c cart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '34D',
                'name' => 'Cuota anuncio c dcart',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '34T',
                'name' => 'Cuota 4 anuncio doble carta',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '35',
                'name' => 'Cuota anuncio c 1/2c',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '36',
                'name' => 'Cuota renta sombrilla',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '37',
                'name' => 'Cuota anuncio revista',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '40',
                'name' => 'Cuota act. dep.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '50',
                'name' => 'Cuota renta raquetas',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '500',
                'name' => 'Cuota c.v. color',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            // [
            //     'code' => '501',
            //     'name' => 'Cuota insc.c.v.colori',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => '502',
                'name' => 'Cuota gtos c.v.colori',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '51',
                'name' => 'Cuota billar',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            // [
            //     'code' => '510',
            //     'name' => 'Cuota insc. futbol dp',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => false,
            // ],
            // [
            //     'code' => '511',
            //     'name' => 'Cuota insc. futbol p1',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => false,
            // ],
            [
                'code' => '541',
                'name' => 'Cuota tenis',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '542',
                'name' => 'Cuota natacion',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '543',
                'name' => 'Cuota curso de verano',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '544',
                'name' => 'Cuota flamenco',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '545',
                'name' => 'Cuota tae kwon do',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '546',
                'name' => 'Cuota futbol dp',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '548',
                'name' => 'Cuota futbol p1',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '549',
                'name' => 'Cuota jazz',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '550',
                'name' => 'Cuota inv. cur.verano',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '551',
                'name' => 'Cuota p1 curs.verano',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '553',
                'name' => 'Cuota spininng',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '554',
                'name' => 'Cuota yoga',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '555',
                'name' => 'Cuota clase spining',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '556',
                'name' => 'Cuota nat. est. inf.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '557',
                'name' => 'Cuota visita spa',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '558',
                'name' => 'Cuota sem c ver',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '559',
                'name' => 'Cuota sem c ver p1',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '560',
                'name' => 'Cuota sem c ver invit',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '561',
                'name' => 'Cuota voleibol',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '562',
                'name' => 'Cuota zumba',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => '60',
                'name' => 'Cuota intercambio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '70',
                'name' => 'Cuota mantto. local',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '703',
                'name' => 'Cuota mantto. local 3',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '707',
                'name' => 'Cuota mantto. local 7',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '708',
                'name' => 'Cuota mantto. local 8',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '709',
                'name' => 'Cuota mantto. local 9',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '710',
                'name' => 'Cuota mantto. local 10',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '711',
                'name' => 'Cuota mantto. local 11',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '712',
                'name' => 'Cuota mantto. local 12',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '713',
                'name' => 'Cuota mantto. local 13',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '714',
                'name' => 'Cuota mantto. local 14',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '715',
                'name' => 'Cuota mantto. local 15',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '716',
                'name' => 'Cuota mantto. local 16',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '717',
                'name' => 'Cuota mantto. local 17',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '718',
                'name' => 'Cuota mantto. local 18',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => true,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => '799',
                'name' => 'Uso de espacio de instalaciones',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            // [
            //     'code' => '80',
            //     'name' => 'Cuota mens parques',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '80I',
            //     'name' => 'Cuota mens parques intermedio',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'code' => '81',
            //     'name' => 'Cuota mens parqes f/i',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => true,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => 'B01',
                'name' => 'Servicio de med. de rehabilitación',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B02',
                'name' => 'Servivio de med. de rehabilitación revaloración',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B03',
                'name' => 'Electromiografía 2 extremidades',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B04',
                'name' => 'Electromiografía 4 extremidades',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B05',
                'name' => 'Aplicación toxina botulínica',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B06',
                'name' => 'Infiltración',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B07',
                'name' => 'Sesión de fisioterapia',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B08',
                'name' => 'Aplicación de tape',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'B09',
                'name' => 'Paq. 10 sesiones de fisioterapia',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'CE',
                'name' => 'Cuota %cons emp h ext',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'CM',
                'name' => 'Cargo por mora',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'CP',
                'name' => 'Cuota % consumo parqu',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'CR',
                'name' => 'Cheque rebotado',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'CR1',
                'name' => 'Cheque rebotado parque 1',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'CTC',
                'name' => 'Comis. t. de c.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            // [
            //     'code' => 'D01',
            //     'name' => 'Devolucion inscripcion',
            //     'description' => null,
            //     'default_amount' => null,
            //     'is_recurring' => false,
            //     'allows_partial_payments' => false,
            //     'is_active' => true,
            // ],
            [
                'code' => 'DE',
                'name' => 'Descuento',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'IF',
                'name' => 'Cuota indiv. a fam.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'PE',
                'name' => 'Pago por usuarios del parque i',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'PS',
                'name' => 'Cuota % sky',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'VA',
                'name' => 'Venta de activo',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'VR',
                'name' => 'Cuota desperfectos',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => false,
            ],
            [
                'code' => 'X02',
                'name' => 'Cuota prom. pub.',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'X03',
                'name' => 'Cuota anuncio revista',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
            [
                'code' => 'X07',
                'name' => 'Patrocinio',
                'description' => null,
                'default_amount' => null,
                'is_recurring' => false,
                'allows_partial_payments' => false,
                'is_active' => true,
            ],
        ];

        foreach ($concepts as $concept) {
            $concept['internal_key'] = $concept['code'];

            ChargeConcept::updateOrCreate(
                ['code' => $concept['code']],
                $concept
            );
        }

    }
}
