<?php

namespace Database\Seeders;

use App\Models\Catalogs\Nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['code' => 'AF', 'name' => 'Afganistan', 'demonym' => 'afgana'],
            ['code' => 'AL', 'name' => 'Albania', 'demonym' => 'albanesa'],
            ['code' => 'DE', 'name' => 'Alemania', 'demonym' => 'alemana'],
            ['code' => 'AD', 'name' => 'Andorra', 'demonym' => 'andorrana'],
            ['code' => 'AO', 'name' => 'Angola', 'demonym' => 'angolena'],
            ['code' => 'AG', 'name' => 'Antigua y Barbuda', 'demonym' => 'antiguana'],
            ['code' => 'SA', 'name' => 'Arabia Saudita', 'demonym' => 'saudi'],
            ['code' => 'DZ', 'name' => 'Argelia', 'demonym' => 'argelina'],
            ['code' => 'AR', 'name' => 'Argentina', 'demonym' => 'argentina'],
            ['code' => 'AM', 'name' => 'Armenia', 'demonym' => 'armenia'],
            ['code' => 'AU', 'name' => 'Australia', 'demonym' => 'australiana'],
            ['code' => 'AT', 'name' => 'Austria', 'demonym' => 'austriaca'],
            ['code' => 'AZ', 'name' => 'Azerbaiyan', 'demonym' => 'azerbaiyana'],
            ['code' => 'BS', 'name' => 'Bahamas', 'demonym' => 'bahamense'],
            ['code' => 'BH', 'name' => 'Barein', 'demonym' => 'bareini'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'demonym' => 'bangladesi'],
            ['code' => 'BB', 'name' => 'Barbados', 'demonym' => 'barbadense'],
            ['code' => 'BE', 'name' => 'Belgica', 'demonym' => 'belga'],
            ['code' => 'BZ', 'name' => 'Belice', 'demonym' => 'belicena'],
            ['code' => 'BJ', 'name' => 'Benin', 'demonym' => 'beninesa'],
            ['code' => 'BY', 'name' => 'Bielorrusia', 'demonym' => 'bielorrusa'],
            ['code' => 'BO', 'name' => 'Bolivia', 'demonym' => 'boliviana'],
            ['code' => 'BA', 'name' => 'Bosnia y Herzegovina', 'demonym' => 'bosnia'],
            ['code' => 'BW', 'name' => 'Botsuana', 'demonym' => 'botsuana'],
            ['code' => 'BR', 'name' => 'Brasil', 'demonym' => 'brasilena'],
            ['code' => 'BN', 'name' => 'Brunei', 'demonym' => 'bruneyana'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'demonym' => 'bulgara'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'demonym' => 'burkinesa'],
            ['code' => 'BI', 'name' => 'Burundi', 'demonym' => 'burundesa'],
            ['code' => 'BT', 'name' => 'Butan', 'demonym' => 'butanesa'],
            ['code' => 'CV', 'name' => 'Cabo Verde', 'demonym' => 'caboverdiana'],
            ['code' => 'KH', 'name' => 'Camboya', 'demonym' => 'camboyana'],
            ['code' => 'CM', 'name' => 'Camerun', 'demonym' => 'camerunesa'],
            ['code' => 'CA', 'name' => 'Canada', 'demonym' => 'canadiense'],
            ['code' => 'QA', 'name' => 'Catar', 'demonym' => 'catari'],
            ['code' => 'TD', 'name' => 'Chad', 'demonym' => 'chadiana'],
            ['code' => 'CL', 'name' => 'Chile', 'demonym' => 'chilena'],
            ['code' => 'CN', 'name' => 'China', 'demonym' => 'china'],
            ['code' => 'CY', 'name' => 'Chipre', 'demonym' => 'chipriota'],
            ['code' => 'VA', 'name' => 'Ciudad del Vaticano', 'demonym' => 'vaticana'],
            ['code' => 'CO', 'name' => 'Colombia', 'demonym' => 'colombiana'],
            ['code' => 'KM', 'name' => 'Comoras', 'demonym' => 'comorense'],
            ['code' => 'KP', 'name' => 'Corea del Norte', 'demonym' => 'norcoreana'],
            ['code' => 'KR', 'name' => 'Corea del Sur', 'demonym' => 'surcoreana'],
            ['code' => 'CI', 'name' => 'Costa de Marfil', 'demonym' => 'marfilena'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'demonym' => 'costarricense'],
            ['code' => 'HR', 'name' => 'Croacia', 'demonym' => 'croata'],
            ['code' => 'CU', 'name' => 'Cuba', 'demonym' => 'cubana'],
            ['code' => 'DK', 'name' => 'Dinamarca', 'demonym' => 'danesa'],
            ['code' => 'DM', 'name' => 'Dominica', 'demonym' => 'dominiquesa'],
            ['code' => 'EC', 'name' => 'Ecuador', 'demonym' => 'ecuatoriana'],
            ['code' => 'EG', 'name' => 'Egipto', 'demonym' => 'egipcia'],
            ['code' => 'SV', 'name' => 'El Salvador', 'demonym' => 'salvadorena'],
            ['code' => 'AE', 'name' => 'Emiratos Arabes Unidos', 'demonym' => 'emirati'],
            ['code' => 'ER', 'name' => 'Eritrea', 'demonym' => 'eritrea'],
            ['code' => 'SK', 'name' => 'Eslovaquia', 'demonym' => 'eslovaca'],
            ['code' => 'SI', 'name' => 'Eslovenia', 'demonym' => 'eslovena'],
            ['code' => 'ES', 'name' => 'Espana', 'demonym' => 'espanola'],
            ['code' => 'US', 'name' => 'Estados Unidos', 'demonym' => 'estadounidense'],
            ['code' => 'EE', 'name' => 'Estonia', 'demonym' => 'estonia'],
            ['code' => 'SZ', 'name' => 'Esuatini', 'demonym' => 'suazi'],
            ['code' => 'ET', 'name' => 'Etiopia', 'demonym' => 'etiope'],
            ['code' => 'PH', 'name' => 'Filipinas', 'demonym' => 'filipina'],
            ['code' => 'FI', 'name' => 'Finlandia', 'demonym' => 'finlandesa'],
            ['code' => 'FJ', 'name' => 'Fiyi', 'demonym' => 'fiyiana'],
            ['code' => 'FR', 'name' => 'Francia', 'demonym' => 'francesa'],
            ['code' => 'GA', 'name' => 'Gabon', 'demonym' => 'gabonesa'],
            ['code' => 'GM', 'name' => 'Gambia', 'demonym' => 'gambiana'],
            ['code' => 'GE', 'name' => 'Georgia', 'demonym' => 'georgiana'],
            ['code' => 'GH', 'name' => 'Ghana', 'demonym' => 'ghanesa'],
            ['code' => 'GD', 'name' => 'Granada', 'demonym' => 'granadina'],
            ['code' => 'GR', 'name' => 'Grecia', 'demonym' => 'griega'],
            ['code' => 'GT', 'name' => 'Guatemala', 'demonym' => 'guatemalteca'],
            ['code' => 'GN', 'name' => 'Guinea', 'demonym' => 'guineana'],
            ['code' => 'GQ', 'name' => 'Guinea Ecuatorial', 'demonym' => 'ecuatoguineana'],
            ['code' => 'GW', 'name' => 'Guinea-Bisau', 'demonym' => 'bisauguineana'],
            ['code' => 'GY', 'name' => 'Guyana', 'demonym' => 'guyanesa'],
            ['code' => 'HT', 'name' => 'Haiti', 'demonym' => 'haitiana'],
            ['code' => 'HN', 'name' => 'Honduras', 'demonym' => 'hondurena'],
            ['code' => 'HU', 'name' => 'Hungria', 'demonym' => 'hungara'],
            ['code' => 'IN', 'name' => 'India', 'demonym' => 'india'],
            ['code' => 'ID', 'name' => 'Indonesia', 'demonym' => 'indonesia'],
            ['code' => 'IQ', 'name' => 'Irak', 'demonym' => 'iraqui'],
            ['code' => 'IR', 'name' => 'Iran', 'demonym' => 'irani'],
            ['code' => 'IE', 'name' => 'Irlanda', 'demonym' => 'irlandesa'],
            ['code' => 'IS', 'name' => 'Islandia', 'demonym' => 'islandesa'],
            ['code' => 'MH', 'name' => 'Islas Marshall', 'demonym' => 'marshalesa'],
            ['code' => 'SB', 'name' => 'Islas Salomon', 'demonym' => 'salomonense'],
            ['code' => 'IL', 'name' => 'Israel', 'demonym' => 'israeli'],
            ['code' => 'IT', 'name' => 'Italia', 'demonym' => 'italiana'],
            ['code' => 'JM', 'name' => 'Jamaica', 'demonym' => 'jamaiquina'],
            ['code' => 'JP', 'name' => 'Japon', 'demonym' => 'japonesa'],
            ['code' => 'JO', 'name' => 'Jordania', 'demonym' => 'jordana'],
            ['code' => 'KZ', 'name' => 'Kazajistan', 'demonym' => 'kazaja'],
            ['code' => 'KE', 'name' => 'Kenia', 'demonym' => 'keniana'],
            ['code' => 'KG', 'name' => 'Kirguistan', 'demonym' => 'kirguisa'],
            ['code' => 'KI', 'name' => 'Kiribati', 'demonym' => 'kiribatiana'],
            ['code' => 'KW', 'name' => 'Kuwait', 'demonym' => 'kuwaiti'],
            ['code' => 'LA', 'name' => 'Laos', 'demonym' => 'laosiana'],
            ['code' => 'LS', 'name' => 'Lesoto', 'demonym' => 'lesotense'],
            ['code' => 'LV', 'name' => 'Letonia', 'demonym' => 'letona'],
            ['code' => 'LB', 'name' => 'Libano', 'demonym' => 'libanesa'],
            ['code' => 'LR', 'name' => 'Liberia', 'demonym' => 'liberiana'],
            ['code' => 'LY', 'name' => 'Libia', 'demonym' => 'libia'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'demonym' => 'liechtensteiniana'],
            ['code' => 'LT', 'name' => 'Lituania', 'demonym' => 'lituana'],
            ['code' => 'LU', 'name' => 'Luxemburgo', 'demonym' => 'luxemburguesa'],
            ['code' => 'MG', 'name' => 'Madagascar', 'demonym' => 'malgache'],
            ['code' => 'MY', 'name' => 'Malasia', 'demonym' => 'malasia'],
            ['code' => 'MW', 'name' => 'Malaui', 'demonym' => 'malaui'],
            ['code' => 'MV', 'name' => 'Maldivas', 'demonym' => 'maldiva'],
            ['code' => 'ML', 'name' => 'Mali', 'demonym' => 'maliense'],
            ['code' => 'MT', 'name' => 'Malta', 'demonym' => 'maltesa'],
            ['code' => 'MA', 'name' => 'Marruecos', 'demonym' => 'marroqui'],
            ['code' => 'MU', 'name' => 'Mauricio', 'demonym' => 'mauriciana'],
            ['code' => 'MR', 'name' => 'Mauritania', 'demonym' => 'mauritana'],
            ['code' => 'MX', 'name' => 'Mexico', 'demonym' => 'mexicana'],
            ['code' => 'FM', 'name' => 'Micronesia', 'demonym' => 'micronesia'],
            ['code' => 'MD', 'name' => 'Moldavia', 'demonym' => 'moldava'],
            ['code' => 'MC', 'name' => 'Monaco', 'demonym' => 'monegasca'],
            ['code' => 'MN', 'name' => 'Mongolia', 'demonym' => 'mongola'],
            ['code' => 'ME', 'name' => 'Montenegro', 'demonym' => 'montenegrina'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'demonym' => 'mozambiquena'],
            ['code' => 'MM', 'name' => 'Myanmar', 'demonym' => 'birmana'],
            ['code' => 'NA', 'name' => 'Namibia', 'demonym' => 'namibia'],
            ['code' => 'NR', 'name' => 'Nauru', 'demonym' => 'nauruana'],
            ['code' => 'NP', 'name' => 'Nepal', 'demonym' => 'nepali'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'demonym' => 'nicaraguense'],
            ['code' => 'NE', 'name' => 'Niger', 'demonym' => 'nigerina'],
            ['code' => 'NG', 'name' => 'Nigeria', 'demonym' => 'nigeriana'],
            ['code' => 'NO', 'name' => 'Noruega', 'demonym' => 'noruega'],
            ['code' => 'NZ', 'name' => 'Nueva Zelanda', 'demonym' => 'neozelandesa'],
            ['code' => 'OM', 'name' => 'Oman', 'demonym' => 'omani'],
            ['code' => 'NL', 'name' => 'Paises Bajos', 'demonym' => 'neerlandesa'],
            ['code' => 'PK', 'name' => 'Pakistan', 'demonym' => 'paquistani'],
            ['code' => 'PW', 'name' => 'Palaos', 'demonym' => 'palauana'],
            ['code' => 'PS', 'name' => 'Palestina', 'demonym' => 'palestina'],
            ['code' => 'PA', 'name' => 'Panama', 'demonym' => 'panamena'],
            ['code' => 'PG', 'name' => 'Papua Nueva Guinea', 'demonym' => 'papuana'],
            ['code' => 'PY', 'name' => 'Paraguay', 'demonym' => 'paraguaya'],
            ['code' => 'PE', 'name' => 'Peru', 'demonym' => 'peruana'],
            ['code' => 'PL', 'name' => 'Polonia', 'demonym' => 'polaca'],
            ['code' => 'PT', 'name' => 'Portugal', 'demonym' => 'portuguesa'],
            ['code' => 'GB', 'name' => 'Reino Unido', 'demonym' => 'britanica'],
            ['code' => 'CF', 'name' => 'Republica Centroafricana', 'demonym' => 'centroafricana'],
            ['code' => 'CZ', 'name' => 'Republica Checa', 'demonym' => 'checa'],
            ['code' => 'CG', 'name' => 'Republica del Congo', 'demonym' => 'congolena'],
            ['code' => 'CD', 'name' => 'Republica Democratica del Congo', 'demonym' => 'congolesa'],
            ['code' => 'DO', 'name' => 'Republica Dominicana', 'demonym' => 'dominicana'],
            ['code' => 'RW', 'name' => 'Ruanda', 'demonym' => 'ruandesa'],
            ['code' => 'RO', 'name' => 'Rumania', 'demonym' => 'rumana'],
            ['code' => 'RU', 'name' => 'Rusia', 'demonym' => 'rusa'],
            ['code' => 'WS', 'name' => 'Samoa', 'demonym' => 'samoana'],
            ['code' => 'KN', 'name' => 'San Cristobal y Nieves', 'demonym' => 'sancristobalense'],
            ['code' => 'SM', 'name' => 'San Marino', 'demonym' => 'sanmarinense'],
            ['code' => 'VC', 'name' => 'San Vicente y las Granadinas', 'demonym' => 'sanvicentina'],
            ['code' => 'LC', 'name' => 'Santa Lucia', 'demonym' => 'santalucense'],
            ['code' => 'ST', 'name' => 'Santo Tome y Principe', 'demonym' => 'santotomesina'],
            ['code' => 'SN', 'name' => 'Senegal', 'demonym' => 'senegalesa'],
            ['code' => 'RS', 'name' => 'Serbia', 'demonym' => 'serbia'],
            ['code' => 'SC', 'name' => 'Seychelles', 'demonym' => 'seychellense'],
            ['code' => 'SL', 'name' => 'Sierra Leona', 'demonym' => 'sierraleonesa'],
            ['code' => 'SG', 'name' => 'Singapur', 'demonym' => 'singapurense'],
            ['code' => 'SY', 'name' => 'Siria', 'demonym' => 'siria'],
            ['code' => 'SO', 'name' => 'Somalia', 'demonym' => 'somali'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'demonym' => 'esrilanquesa'],
            ['code' => 'ZA', 'name' => 'Sudafrica', 'demonym' => 'sudafricana'],
            ['code' => 'SD', 'name' => 'Sudan', 'demonym' => 'sudanesa'],
            ['code' => 'SS', 'name' => 'Sudan del Sur', 'demonym' => 'sursudanesa'],
            ['code' => 'SE', 'name' => 'Suecia', 'demonym' => 'sueca'],
            ['code' => 'CH', 'name' => 'Suiza', 'demonym' => 'suiza'],
            ['code' => 'SR', 'name' => 'Surinam', 'demonym' => 'surinamesa'],
            ['code' => 'TH', 'name' => 'Tailandia', 'demonym' => 'tailandesa'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'demonym' => 'tanzana'],
            ['code' => 'TJ', 'name' => 'Tayikistan', 'demonym' => 'tayika'],
            ['code' => 'TL', 'name' => 'Timor Oriental', 'demonym' => 'timorense'],
            ['code' => 'TG', 'name' => 'Togo', 'demonym' => 'togolesa'],
            ['code' => 'TO', 'name' => 'Tonga', 'demonym' => 'tongana'],
            ['code' => 'TT', 'name' => 'Trinidad y Tobago', 'demonym' => 'trinitense'],
            ['code' => 'TN', 'name' => 'Tunez', 'demonym' => 'tunecina'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'demonym' => 'turcomana'],
            ['code' => 'TR', 'name' => 'Turquia', 'demonym' => 'turca'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'demonym' => 'tuvaluana'],
            ['code' => 'UA', 'name' => 'Ucrania', 'demonym' => 'ucraniana'],
            ['code' => 'UG', 'name' => 'Uganda', 'demonym' => 'ugandesa'],
            ['code' => 'UY', 'name' => 'Uruguay', 'demonym' => 'uruguaya'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'demonym' => 'uzbeka'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'demonym' => 'vanuatense'],
            ['code' => 'VE', 'name' => 'Venezuela', 'demonym' => 'venezolana'],
            ['code' => 'VN', 'name' => 'Vietnam', 'demonym' => 'vietnamita'],
            ['code' => 'YE', 'name' => 'Yemen', 'demonym' => 'yemeni'],
            ['code' => 'DJ', 'name' => 'Yibuti', 'demonym' => 'yibutiana'],
            ['code' => 'ZM', 'name' => 'Zambia', 'demonym' => 'zambiana'],
            ['code' => 'ZW', 'name' => 'Zimbabue', 'demonym' => 'zimbabuense'],
        ];

        foreach ($nationalities as $nationality) {
            Nationality::updateOrCreate(
                ['code' => $nationality['code']],
                [
                    'name' => $nationality['name'],
                    'demonym' => $nationality['demonym'],
                ]
            );
        }
    }
}
