<?php

namespace Database\Seeders;

use App\Models\Catalogs\Nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['code' => 'AF', 'name' => 'Afganistan', 'demonym' => 'afgano'],
            ['code' => 'AL', 'name' => 'Albania', 'demonym' => 'albanes'],
            ['code' => 'DE', 'name' => 'Alemania', 'demonym' => 'aleman'],
            ['code' => 'AD', 'name' => 'Andorra', 'demonym' => 'andorrano'],
            ['code' => 'AO', 'name' => 'Angola', 'demonym' => 'angoleno'],
            ['code' => 'AG', 'name' => 'Antigua y Barbuda', 'demonym' => 'antiguano'],
            ['code' => 'SA', 'name' => 'Arabia Saudita', 'demonym' => 'saudi'],
            ['code' => 'DZ', 'name' => 'Argelia', 'demonym' => 'argelino'],
            ['code' => 'AR', 'name' => 'Argentina', 'demonym' => 'argentino'],
            ['code' => 'AM', 'name' => 'Armenia', 'demonym' => 'armenio'],
            ['code' => 'AU', 'name' => 'Australia', 'demonym' => 'australiano'],
            ['code' => 'AT', 'name' => 'Austria', 'demonym' => 'austriaco'],
            ['code' => 'AZ', 'name' => 'Azerbaiyan', 'demonym' => 'azerbaiyano'],
            ['code' => 'BS', 'name' => 'Bahamas', 'demonym' => 'bahamense'],
            ['code' => 'BH', 'name' => 'Barein', 'demonym' => 'bareini'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'demonym' => 'bangladesi'],
            ['code' => 'BB', 'name' => 'Barbados', 'demonym' => 'barbadense'],
            ['code' => 'BE', 'name' => 'Belgica', 'demonym' => 'belga'],
            ['code' => 'BZ', 'name' => 'Belice', 'demonym' => 'beliceno'],
            ['code' => 'BJ', 'name' => 'Benin', 'demonym' => 'benines'],
            ['code' => 'BY', 'name' => 'Bielorrusia', 'demonym' => 'bielorruso'],
            ['code' => 'BO', 'name' => 'Bolivia', 'demonym' => 'boliviano'],
            ['code' => 'BA', 'name' => 'Bosnia y Herzegovina', 'demonym' => 'bosnio'],
            ['code' => 'BW', 'name' => 'Botsuana', 'demonym' => 'botsuano'],
            ['code' => 'BR', 'name' => 'Brasil', 'demonym' => 'brasileno'],
            ['code' => 'BN', 'name' => 'Brunei', 'demonym' => 'bruneyano'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'demonym' => 'bulgaro'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'demonym' => 'burkines'],
            ['code' => 'BI', 'name' => 'Burundi', 'demonym' => 'burundes'],
            ['code' => 'BT', 'name' => 'Butan', 'demonym' => 'butanes'],
            ['code' => 'CV', 'name' => 'Cabo Verde', 'demonym' => 'caboverdiano'],
            ['code' => 'KH', 'name' => 'Camboya', 'demonym' => 'camboyano'],
            ['code' => 'CM', 'name' => 'Camerun', 'demonym' => 'camerunes'],
            ['code' => 'CA', 'name' => 'Canada', 'demonym' => 'canadiense'],
            ['code' => 'QA', 'name' => 'Catar', 'demonym' => 'catari'],
            ['code' => 'TD', 'name' => 'Chad', 'demonym' => 'chadiano'],
            ['code' => 'CL', 'name' => 'Chile', 'demonym' => 'chileno'],
            ['code' => 'CN', 'name' => 'China', 'demonym' => 'chino'],
            ['code' => 'CY', 'name' => 'Chipre', 'demonym' => 'chipriota'],
            ['code' => 'VA', 'name' => 'Ciudad del Vaticano', 'demonym' => 'vaticano'],
            ['code' => 'CO', 'name' => 'Colombia', 'demonym' => 'colombiano'],
            ['code' => 'KM', 'name' => 'Comoras', 'demonym' => 'comorense'],
            ['code' => 'KP', 'name' => 'Corea del Norte', 'demonym' => 'norcoreano'],
            ['code' => 'KR', 'name' => 'Corea del Sur', 'demonym' => 'surcoreano'],
            ['code' => 'CI', 'name' => 'Costa de Marfil', 'demonym' => 'marfileno'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'demonym' => 'costarricense'],
            ['code' => 'HR', 'name' => 'Croacia', 'demonym' => 'croata'],
            ['code' => 'CU', 'name' => 'Cuba', 'demonym' => 'cubano'],
            ['code' => 'DK', 'name' => 'Dinamarca', 'demonym' => 'danes'],
            ['code' => 'DM', 'name' => 'Dominica', 'demonym' => 'dominiques'],
            ['code' => 'EC', 'name' => 'Ecuador', 'demonym' => 'ecuatoriano'],
            ['code' => 'EG', 'name' => 'Egipto', 'demonym' => 'egipcio'],
            ['code' => 'SV', 'name' => 'El Salvador', 'demonym' => 'salvadoreno'],
            ['code' => 'AE', 'name' => 'Emiratos Arabes Unidos', 'demonym' => 'emirati'],
            ['code' => 'ER', 'name' => 'Eritrea', 'demonym' => 'eritreo'],
            ['code' => 'SK', 'name' => 'Eslovaquia', 'demonym' => 'eslovaco'],
            ['code' => 'SI', 'name' => 'Eslovenia', 'demonym' => 'esloveno'],
            ['code' => 'ES', 'name' => 'Espana', 'demonym' => 'espanol'],
            ['code' => 'US', 'name' => 'Estados Unidos', 'demonym' => 'estadounidense'],
            ['code' => 'EE', 'name' => 'Estonia', 'demonym' => 'estonio'],
            ['code' => 'SZ', 'name' => 'Esuatini', 'demonym' => 'suazi'],
            ['code' => 'ET', 'name' => 'Etiopia', 'demonym' => 'etiope'],
            ['code' => 'PH', 'name' => 'Filipinas', 'demonym' => 'filipino'],
            ['code' => 'FI', 'name' => 'Finlandia', 'demonym' => 'finlandes'],
            ['code' => 'FJ', 'name' => 'Fiyi', 'demonym' => 'fiyiano'],
            ['code' => 'FR', 'name' => 'Francia', 'demonym' => 'frances'],
            ['code' => 'GA', 'name' => 'Gabon', 'demonym' => 'gabones'],
            ['code' => 'GM', 'name' => 'Gambia', 'demonym' => 'gambiano'],
            ['code' => 'GE', 'name' => 'Georgia', 'demonym' => 'georgiano'],
            ['code' => 'GH', 'name' => 'Ghana', 'demonym' => 'ghanes'],
            ['code' => 'GD', 'name' => 'Granada', 'demonym' => 'granadino'],
            ['code' => 'GR', 'name' => 'Grecia', 'demonym' => 'griego'],
            ['code' => 'GT', 'name' => 'Guatemala', 'demonym' => 'guatemalteco'],
            ['code' => 'GN', 'name' => 'Guinea', 'demonym' => 'guineano'],
            ['code' => 'GQ', 'name' => 'Guinea Ecuatorial', 'demonym' => 'ecuatoguineano'],
            ['code' => 'GW', 'name' => 'Guinea-Bisau', 'demonym' => 'bisauguineano'],
            ['code' => 'GY', 'name' => 'Guyana', 'demonym' => 'guyanes'],
            ['code' => 'HT', 'name' => 'Haiti', 'demonym' => 'haitiano'],
            ['code' => 'HN', 'name' => 'Honduras', 'demonym' => 'hondureno'],
            ['code' => 'HU', 'name' => 'Hungria', 'demonym' => 'hungaro'],
            ['code' => 'IN', 'name' => 'India', 'demonym' => 'indio'],
            ['code' => 'ID', 'name' => 'Indonesia', 'demonym' => 'indonesio'],
            ['code' => 'IQ', 'name' => 'Irak', 'demonym' => 'iraqui'],
            ['code' => 'IR', 'name' => 'Iran', 'demonym' => 'irani'],
            ['code' => 'IE', 'name' => 'Irlanda', 'demonym' => 'irlandes'],
            ['code' => 'IS', 'name' => 'Islandia', 'demonym' => 'islandes'],
            ['code' => 'MH', 'name' => 'Islas Marshall', 'demonym' => 'marshales'],
            ['code' => 'SB', 'name' => 'Islas Salomon', 'demonym' => 'salomonense'],
            ['code' => 'IL', 'name' => 'Israel', 'demonym' => 'israeli'],
            ['code' => 'IT', 'name' => 'Italia', 'demonym' => 'italiano'],
            ['code' => 'JM', 'name' => 'Jamaica', 'demonym' => 'jamaiquino'],
            ['code' => 'JP', 'name' => 'Japon', 'demonym' => 'japones'],
            ['code' => 'JO', 'name' => 'Jordania', 'demonym' => 'jordano'],
            ['code' => 'KZ', 'name' => 'Kazajistan', 'demonym' => 'kazajo'],
            ['code' => 'KE', 'name' => 'Kenia', 'demonym' => 'keniano'],
            ['code' => 'KG', 'name' => 'Kirguistan', 'demonym' => 'kirguis'],
            ['code' => 'KI', 'name' => 'Kiribati', 'demonym' => 'kiribatiano'],
            ['code' => 'KW', 'name' => 'Kuwait', 'demonym' => 'kuwaiti'],
            ['code' => 'LA', 'name' => 'Laos', 'demonym' => 'laosiano'],
            ['code' => 'LS', 'name' => 'Lesoto', 'demonym' => 'lesotense'],
            ['code' => 'LV', 'name' => 'Letonia', 'demonym' => 'leton'],
            ['code' => 'LB', 'name' => 'Libano', 'demonym' => 'libanes'],
            ['code' => 'LR', 'name' => 'Liberia', 'demonym' => 'liberiano'],
            ['code' => 'LY', 'name' => 'Libia', 'demonym' => 'libio'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'demonym' => 'liechtensteiniano'],
            ['code' => 'LT', 'name' => 'Lituania', 'demonym' => 'lituano'],
            ['code' => 'LU', 'name' => 'Luxemburgo', 'demonym' => 'luxemburgues'],
            ['code' => 'MG', 'name' => 'Madagascar', 'demonym' => 'malgache'],
            ['code' => 'MY', 'name' => 'Malasia', 'demonym' => 'malasio'],
            ['code' => 'MW', 'name' => 'Malaui', 'demonym' => 'malaui'],
            ['code' => 'MV', 'name' => 'Maldivas', 'demonym' => 'maldivo'],
            ['code' => 'ML', 'name' => 'Mali', 'demonym' => 'maliense'],
            ['code' => 'MT', 'name' => 'Malta', 'demonym' => 'maltes'],
            ['code' => 'MA', 'name' => 'Marruecos', 'demonym' => 'marroqui'],
            ['code' => 'MU', 'name' => 'Mauricio', 'demonym' => 'mauriciano'],
            ['code' => 'MR', 'name' => 'Mauritania', 'demonym' => 'mauritano'],
            ['code' => 'MX', 'name' => 'Mexico', 'demonym' => 'mexicano'],
            ['code' => 'FM', 'name' => 'Micronesia', 'demonym' => 'micronesio'],
            ['code' => 'MD', 'name' => 'Moldavia', 'demonym' => 'moldavo'],
            ['code' => 'MC', 'name' => 'Monaco', 'demonym' => 'monegasco'],
            ['code' => 'MN', 'name' => 'Mongolia', 'demonym' => 'mongol'],
            ['code' => 'ME', 'name' => 'Montenegro', 'demonym' => 'montenegrino'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'demonym' => 'mozambiqueno'],
            ['code' => 'MM', 'name' => 'Myanmar', 'demonym' => 'birmano'],
            ['code' => 'NA', 'name' => 'Namibia', 'demonym' => 'namibio'],
            ['code' => 'NR', 'name' => 'Nauru', 'demonym' => 'nauruano'],
            ['code' => 'NP', 'name' => 'Nepal', 'demonym' => 'nepali'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'demonym' => 'nicaraguense'],
            ['code' => 'NE', 'name' => 'Niger', 'demonym' => 'nigerino'],
            ['code' => 'NG', 'name' => 'Nigeria', 'demonym' => 'nigeriano'],
            ['code' => 'NO', 'name' => 'Noruega', 'demonym' => 'noruego'],
            ['code' => 'NZ', 'name' => 'Nueva Zelanda', 'demonym' => 'neozelandes'],
            ['code' => 'OM', 'name' => 'Oman', 'demonym' => 'omani'],
            ['code' => 'NL', 'name' => 'Paises Bajos', 'demonym' => 'neerlandes'],
            ['code' => 'PK', 'name' => 'Pakistan', 'demonym' => 'paquistani'],
            ['code' => 'PW', 'name' => 'Palaos', 'demonym' => 'palauano'],
            ['code' => 'PS', 'name' => 'Palestina', 'demonym' => 'palestino'],
            ['code' => 'PA', 'name' => 'Panama', 'demonym' => 'panameno'],
            ['code' => 'PG', 'name' => 'Papua Nueva Guinea', 'demonym' => 'papuano'],
            ['code' => 'PY', 'name' => 'Paraguay', 'demonym' => 'paraguayo'],
            ['code' => 'PE', 'name' => 'Peru', 'demonym' => 'peruano'],
            ['code' => 'PL', 'name' => 'Polonia', 'demonym' => 'polaco'],
            ['code' => 'PT', 'name' => 'Portugal', 'demonym' => 'portugues'],
            ['code' => 'GB', 'name' => 'Reino Unido', 'demonym' => 'britanico'],
            ['code' => 'CF', 'name' => 'Republica Centroafricana', 'demonym' => 'centroafricano'],
            ['code' => 'CZ', 'name' => 'Republica Checa', 'demonym' => 'checo'],
            ['code' => 'CG', 'name' => 'Republica del Congo', 'demonym' => 'congoleno'],
            ['code' => 'CD', 'name' => 'Republica Democratica del Congo', 'demonym' => 'congoles'],
            ['code' => 'DO', 'name' => 'Republica Dominicana', 'demonym' => 'dominicano'],
            ['code' => 'RW', 'name' => 'Ruanda', 'demonym' => 'ruandes'],
            ['code' => 'RO', 'name' => 'Rumania', 'demonym' => 'rumano'],
            ['code' => 'RU', 'name' => 'Rusia', 'demonym' => 'ruso'],
            ['code' => 'WS', 'name' => 'Samoa', 'demonym' => 'samoano'],
            ['code' => 'KN', 'name' => 'San Cristobal y Nieves', 'demonym' => 'sancristobalense'],
            ['code' => 'SM', 'name' => 'San Marino', 'demonym' => 'sanmarinense'],
            ['code' => 'VC', 'name' => 'San Vicente y las Granadinas', 'demonym' => 'sanvicentino'],
            ['code' => 'LC', 'name' => 'Santa Lucia', 'demonym' => 'santalucense'],
            ['code' => 'ST', 'name' => 'Santo Tome y Principe', 'demonym' => 'santotomesino'],
            ['code' => 'SN', 'name' => 'Senegal', 'demonym' => 'senegales'],
            ['code' => 'RS', 'name' => 'Serbia', 'demonym' => 'serbio'],
            ['code' => 'SC', 'name' => 'Seychelles', 'demonym' => 'seychellense'],
            ['code' => 'SL', 'name' => 'Sierra Leona', 'demonym' => 'sierraleones'],
            ['code' => 'SG', 'name' => 'Singapur', 'demonym' => 'singapurense'],
            ['code' => 'SY', 'name' => 'Siria', 'demonym' => 'sirio'],
            ['code' => 'SO', 'name' => 'Somalia', 'demonym' => 'somali'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'demonym' => 'esrilanques'],
            ['code' => 'ZA', 'name' => 'Sudafrica', 'demonym' => 'sudafricano'],
            ['code' => 'SD', 'name' => 'Sudan', 'demonym' => 'sudanes'],
            ['code' => 'SS', 'name' => 'Sudan del Sur', 'demonym' => 'sursudanes'],
            ['code' => 'SE', 'name' => 'Suecia', 'demonym' => 'sueco'],
            ['code' => 'CH', 'name' => 'Suiza', 'demonym' => 'suizo'],
            ['code' => 'SR', 'name' => 'Surinam', 'demonym' => 'surinames'],
            ['code' => 'TH', 'name' => 'Tailandia', 'demonym' => 'tailandes'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'demonym' => 'tanzano'],
            ['code' => 'TJ', 'name' => 'Tayikistan', 'demonym' => 'tayiko'],
            ['code' => 'TL', 'name' => 'Timor Oriental', 'demonym' => 'timorense'],
            ['code' => 'TG', 'name' => 'Togo', 'demonym' => 'togoles'],
            ['code' => 'TO', 'name' => 'Tonga', 'demonym' => 'tongano'],
            ['code' => 'TT', 'name' => 'Trinidad y Tobago', 'demonym' => 'trinitense'],
            ['code' => 'TN', 'name' => 'Tunez', 'demonym' => 'tunecino'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'demonym' => 'turcomano'],
            ['code' => 'TR', 'name' => 'Turquia', 'demonym' => 'turco'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'demonym' => 'tuvaluano'],
            ['code' => 'UA', 'name' => 'Ucrania', 'demonym' => 'ucraniano'],
            ['code' => 'UG', 'name' => 'Uganda', 'demonym' => 'ugandes'],
            ['code' => 'UY', 'name' => 'Uruguay', 'demonym' => 'uruguayo'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'demonym' => 'uzbeko'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'demonym' => 'vanuatense'],
            ['code' => 'VE', 'name' => 'Venezuela', 'demonym' => 'venezolano'],
            ['code' => 'VN', 'name' => 'Vietnam', 'demonym' => 'vietnamita'],
            ['code' => 'YE', 'name' => 'Yemen', 'demonym' => 'yemeni'],
            ['code' => 'DJ', 'name' => 'Yibuti', 'demonym' => 'yibutiano'],
            ['code' => 'ZM', 'name' => 'Zambia', 'demonym' => 'zambiano'],
            ['code' => 'ZW', 'name' => 'Zimbabue', 'demonym' => 'zimbabuense'],
        ];

        foreach ($nationalities as $nationality) {
            Nationality::updateOrCreate(
                ['code' => $nationality['code']],
                [
                    'name' => $nationality['name'],
                    'demonym' => $nationality['demonym'],
                ]
            );
        }
    }
}
